class UserAlreadyExists(Exception): ...
  
class UserNotFound(Exception): ...

class IncorrectPassword(Exception): ...

class RefreshTokenNotFound(Exception): ...

class InvalidRefreshToken(Exception): ...
  

class IncorrectNumberOfFiles(Exception): ...

class FileTooLarge(Exception): ...

class IncorrectFileFormat(Exception): ...

class FileAlreadyExists(Exception): ...

class FileMustHaveAName(Exception): ...

class FileNotFound(Exception): ...


class FolderAlreadyExists(Exception): ...

class FolderNotFound(Exception): ...


class InternalServerError(Exception): ...